### ISSUE TITLE
Game crashes with this mod installed on 1.19.3 when opening inventory

### ISSUE THREAD

**Issue by CalXee** [Mrredstone5230/Ctrl-Q#5]
On the latest version, if you have this mod installed and open your inventory, the game will crash.

**Comment by SB2DD** [comment]
Alright I'll check this out. I didn't know 1.19.3 was out yet

**Comment by SB2DD** [comment]
I'm very sorry, but I cannot reproduce this issue. What mods do you have installed?

**Comment by SB2DD** [comment]
I will be closing this issue. Please comment back if the crashing still occurs.

**Comment by CalXee** [comment]
Sorry I've been busy, here's crash logs

https://pastebin.com/D2U6G4Z8

**Comment by SB2DD** [comment]
Huh, this is weird, because now I'm getting the issue.. I must of been testing the wrong MC version :/   Anyways, I'm looking into it.

**Comment by SB2DD** [comment]
Alright, fixed with v1.9. Thank you so much for reporting this and I deeply apologize for mistakenly marking this as resolved. 

https://github.com/Mrredstone5230/Ctrl-Q/releases/tag/1.9
